# Generated by Django 5.2.4 on 2025-08-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadOMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='uploads/')),
                ('nota', models.FloatField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
